import { type Module, inject } from 'langium';
import { createDefaultModule, createDefaultSharedModule, type DefaultSharedModuleContext, type LangiumServices, type LangiumSharedServices, type PartialLangiumServices } from 'langium/lsp';
import { SmtLibGeneratedModule, SmtLibGeneratedSharedModule } from './generated/module.js';
import { SmtLibValidator, registerValidationChecks } from './smt-lib-validator.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type SmtLibAddedServices = {
    validation: {
        SmtLibValidator: SmtLibValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type SmtLibServices = LangiumServices & SmtLibAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const SmtLibModule: Module<SmtLibServices, PartialLangiumServices & SmtLibAddedServices> = {
    validation: {
        SmtLibValidator: () => new SmtLibValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createSmtLibServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    SmtLib: SmtLibServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        SmtLibGeneratedSharedModule
    );
    const SmtLib = inject(
        createDefaultModule({ shared }),
        SmtLibGeneratedModule,
        SmtLibModule
    );
    shared.ServiceRegistry.register(SmtLib);
    registerValidationChecks(SmtLib);
    if (!context.connection) {
        // We don't run inside a language server
        // Therefore, initialize the configuration provider instantly
        shared.workspace.ConfigurationProvider.initialized({});
    }
    return { shared, SmtLib };
}
